#!/bin/bash

if [ "$EUID" -eq 0 ]; then
    echo "Please don't run this as root."
    exit 1
fi

set -euxo pipefail

mkdir -p ~/.local/bin
rm ~/.bashrc ~/.bash_profile
stow Home -t ~/

ln -s /usr/bin/kitty ~/.local/bin/gnome-terminal

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak remote-modify flathub --enable

flatpak install -y flathub org.gtk.Gtk3theme.adw-gtk3 org.gtk.Gtk3theme.adw-gtk3-dark

flatpak install -y flathub com.mattjakeman.ExtensionManager com.valvesoftware.Steam \
	com.modrinth.ModrinthApp com.github.tchx84.Flatseal \
	org.gnome.World.Secrets org.chromium.Chromium de.haeckerfelix.Fragments \
	org.gnome.Showtime org.gnome.Decibels org.gnome.Papers org.gnome.Loupe \
	org.gnome.clocks org.gnome.Calendar
