#!/bin/bash

if [ "$EUID" -ne 0 ]; then
  echo "Please run this as root."
  exit 1
fi

set -euxo pipefail

dnf upgrade -y

dnf remove -y gnome-contacts gnome-weather gnome-maps simple-scan snapshot \
	gnome-connections baobab gnome-logs gnome-abrt libreoffice-* gnome-tour \
	yelp firefox gnome-boxes ptyxis

dnf install -y stow podman-compose @development-tools golang virt-manager wireshark \
	kubernetes1.33-client ansible opentofu helm wl-clipboard adw-gtk3-theme \
	gnome-tweaks SDL2-devel kitty cascadia-code-nf-fonts

usermod -aG libvirt melonlorrd
usermod -aG wireshark melonlorrd
